### ISSUE TITLE
Implement shortcut for wrapping text in texttt

### ISSUE THREAD

**Issue by cogitantium** [hrjakobsen/slext#67] opened 2019-11-13 13:38 UTC
When writing computer science stuff I often use `\texttt{}` and miss the Markdown backticks. Could Slext intercept these and auto-complete an _unclosed_ backtick with `\texttt{$contents}`?

Maybe the `alt + c` command could be utilised for this.

**Comment by hrjakobsen** [comment] 2019-11-13 13:43
I'm not sure if this is 1 suggestion or two separate questions. alt+c can be used to wrap in `\texttt` as you suggest, but you'd have to write the `texttt` each time.  

We _could_ add something to intercept ` characters, but it would be very difficult to ensure that this is done correctly, (it should not happen when inside a lstlisting/minted environment for example).

**Comment by hrjakobsen** [comment] 2019-11-13 13:45
We could potentially expand the number of shortcuts already in the editor (`ctrl+b` for bold, `ctrl+i` for italics), but we should probably avoid overriding `ctrl+t` for typewriter font.

**Comment by cogitantium** [comment] 2019-11-13 14:07
Just one question - whether it's possible to implement a better shorthand for texttt than writing the text, marking, `alt+c`, and writing 'texttt'. 

Finding an unused `ctrl+` and `alt+` shortcut across all locales is probably difficult but we might be okay to override a lesser used one, such as `alt+h` for Help in Firefox. 
Yet this would still need marking of the text to be enclosed in a 'texttt' command, which is an improvement but no auto-completion.

**Comment by hrjakobsen** [comment] 2019-11-13 14:11
Well if we were to implement it like `ctrl+b`/`ctrl+i` typing the command without any text selected, it inserts `\textbf{|}`with the cursor at the | position. That would eliminate the text selection.

**Comment by cogitantium** [comment] 2019-11-13 14:15
That would be very cool :+1:

**Comment by hrjakobsen** [comment] 2019-11-13 14:23
I found the (compiled) source code for adding the command in the Overleaf, so we should be able to add this to SLext as well.

```javascript
L.commands.addCommand(
    {
        name:"bold",
        bindKey: {
            win:"Ctrl-B",
            mac:"Command-B"
        },
        exec: function(e){
            if(e.getSelection().isEmpty()) 
                return e.insert("\\textbf{}"), e.navigateLeft(1); 
            var t=e.getCopyText();
            return e.insert("\\textbf{".concat(t,"}"))
        },
        readOnly:!1
    })
```

**Comment by hrjakobsen** [comment] 2019-11-13 14:25
I also found the very similar non-compiled code at https://github.com/overleaf/web/blob/9e07a7d040d6cf61ef92015665f7d65b45241188/frontend/js/ide/editor/directives/aceEditor.js#L299

**Comment by Hense94** [comment] 2019-12-18 13:51
Now that we are three days away from deadline and therefore have begun writing our paper, I would also appreciate if this shortcut was implemented.

**Comment by hrjakobsen** [comment] 2019-12-18 15:08
@Hense94 

> Deadline for handing in the project: 15 January at 12.00

You have plenty of time for writing "texttt" 🤔

**Comment by hrjakobsen** [comment] 2019-12-20 12:26
I wonder if we should just prefill the prompt with the previously used command. If the use-case is to use the same command multiple times, this may solve it?

**Comment by cogitantium** [comment] 2019-12-22 17:07
> I wonder if we should just prefill the prompt with the previously used command. If the use-case is to use the same command multiple times, this may solve it?

Prefilling `alt+c` is a nice feature which does solve the issue but I think I would still prefer a dedicated command, just like bold and italics.

Side note; invoking `alt+c` and entering no command simply drops a `{}` at the cursor - is this intended behaviour?

**Comment by hrjakobsen** [comment] 2019-12-22 17:21
Yes this was intended to wrap the selection in {}. Maybe this shouldn't happen if the selection is empty?

**Comment by cogitantium** [comment] 2019-12-22 18:39
Oh, on a selection it does make sense, if you want to mark a section and wrap it in braces, e.g. one part of a `\frac`.

Invoking `alt+c` on no selection, writing no command, and putting enter feels like a way to exit the dialog without doing any changes - `esc` works as intended here - but that's my intuition.

**Comment by hrjakobsen** [comment] 2019-12-27 17:26
I've cleaned up the code of the wrapping command in 560b4e8, and it now suggests the last entered command in the prompt.  

This is the current behaviour (`|` is the cursor position):

- `text` → `\command{text}|`
- `|` → `\command{|}`
- `text` → `{text}|`
- `|` → `{|}`
- `|`  (ESC) → `|`
- `text`  (ESC) → `text`

**Comment by hrjakobsen** [comment] 2019-12-27 17:30
Also I'm closing the issue for now as it seemed to resolve the issue (at least somewhat). I'll open it again if there is still need for more work to be done.

**Closed by hrjakobsen** 2019-12-27 17:30 UTC
