### ISSUE TITLE
buttons to switch tabs do not work

### ISSUE THREAD

**Issue by maiermic** [hrjakobsen/slext#61] opened 2019-03-08 13:28 UTC
I expect the buttons with class `slext-tabs__caret--next` and `slext-tabs__caret--prev` to change the active tab (next/previous), but they only scroll left/right.

**Comment by hrjakobsen** [comment] 2019-03-09 07:28
They do work as intended. The buttons shows the next and/or previous set of tabs. I will close this issue, as I don't see any problem to be solved. Switching to the next tab is already tracked in #58.

**Closed by hrjakobsen** 2019-03-09 07:28 UTC

**Comment by maiermic** [comment] 2019-03-09 08:16
I see. I misinterpreted this function.
